// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqtrqyofpajeqifkqtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncXRycXlvZnBhamVxaWZrcXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDk2MDIsImV4cCI6MjA2MDcyNTYwMn0.9tvm5VhyaHNDV956FIRgj3xoCBI32j26wpJzx9RHeUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);